### ISSUE TITLE
No such container: wordpressfiles

### ISSUE THREAD

**Issue by izzoa** [rija/docker-nginx-fpm-caches-wordpress#6]
Not sure if I missed a step here, but on a fresh installation of Ubuntu 16.04 + docker, running the docker run command gives me "No such container: wordpressfiles". 

Further, if I exclude the line "--volumes-from wordpressfiles," the container starts normally but accessing my domain redirects to "https://server_fqdn/." docker logs doesn't show anything suspicious either.

Did I miss something?

**Comment by rija** [comment]
When using ``--volumes-from wordpressfiles``, it expects a Data Volume Container to exists like this:

```bash
$ docker create --name wordpressfiles -v /usr/share/nginx/www rija/docker-nginx-fpm-caches-wordpress
```

Note, that the use of Data Volume Containers is no longer recommended by Docker so I phased it out  but I've left some references in the README inadvertently. I'll remove the remaining references shortly.

Therefore it's fine and preferred to drop out the ``--volumes-from wordpressfiles`` entirely and it will still works fine.

make sure you pass  to ``docker run``,  the argument ``--env SERVER_NAME=example.com`` where **example.com** is replaced by your domain name, the [bootstrap.sh](https://github.com/rija/docker-nginx-fpm-caches-wordpress/blob/master/bootstrap.sh) script  will replace occurrences of **server_fqdn** by the domain name you supply there.

When using the ``docker run`` command, it also expects that a container  running with mysql or mariadb exists too. 

A full working example on how it  could be used can be seen in the [build log](https://travis-ci.org/rija/docker-nginx-fpm-caches-wordpress/builds/232651857) of our continuous integration testing instance on Travis-Ci.

However the easiest way to get a full Wordpress install running is to use ``docker-compose``. 

Also please note, that I'm working on  major changes on how this Dockerfile is operated, so the actual modus operandi and documentation may be out of sync for awhile. 

The Travis-CI test configuration will be the most up-to-date source for how to use this Dockerfile during that time.
